### ISSUE TITLE
Read Correct NOAA Path from Config

### ISSUE THREAD

**Issue by vahid-dan** [FLARE-forecast/FLARE-containers#9]
Update `flare-process-noaa` code to use the following parameters from the config file to read correct NOAA path:

```YAML
noaa_model: NOAAGEFS_6hr
lake_name_code: fcre
```

https://github.com/FLARE-forecast/FLARE-containers/commit/b6c25e3a116871bd1ab32c34a6e15c745331f47a#diff-2a41acdfed71ad340a64c8d2955df241c4e4bdd4bb83385d67d008452c7846de

**Comment by Yun-Jung** [comment]
@vahid-dan Done!

**Comment by vahid-dan** [comment]
Completed
